

language: c

cache: ccache
cache:
  directories:
  - .cache

matrix:
  include:
    # Build and test against the master (stable) and devel branches of Nim
    - os: linux
      env: CHANNEL=stable
      compiler: gcc
      addons: # This will only be executed on Linux
        apt:
          packages:
            - libgtk-3-dev 
            - libwebkit2gtk-4.0-dev

    - os: linux
      env: CHANNEL=devel
      compiler: gcc
      addons: # This will only be executed on Linux
        apt:
          packages:
            - libgtk-3-dev 
            - libwebkit2gtk-4.0-dev

    - os: linux
      env: CHANNEL=stable CROSS_CPU=arm
      compiler: gcc
      addons: # This will only be executed on Linux
        apt:
          packages:
            - gcc-arm-linux-gnueabihf

    - os: linux
      env: CHANNEL=stable CROSS_CPU=powerpc64el
      compiler: gcc
      sudo: true
      addons: # This will only be executed on Linux
        apt:
          packages:
            - gcc-powerpc64le-linux-gnu
            - libc6-dev-ppc64el-cross

    - os: linux
      env: CHANNEL=stable CROSS_OS=windows
      compiler: gcc
      addons: # This will only be executed on Linux
        apt:
          packages:
            - mingw-w64

    # On OSX we only test against clang (gcc is mapped to clang by default)
    - os: osx
      env: CHANNEL=stable
      compiler: clang

  allow_failures:
    # Ignore failures when building against the devel Nim branch
    - env: CHANNEL=devel
    # allow arm to fail for integer conversion
    - env: CHANNEL=stable CROSS_CPU=arm

  fast_finish: true


install:
  - export CHOOSENIM_NO_ANALYTICS=1
  - export PATH=~/.nimble/bin:$PATH
  - sh ci/install.sh

script:
  - nimble --version
  - nim --version
  - nimble refresh
  - sh ci/test.sh
  - sh ci/build.sh

before_deploy:
  - ls
  - sh ci/before_deploy.sh
  - ls deploy

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: deploy/*
  skip_cleanup: true
  on:
    tags: true
  draft: true

branches:
  except:
    - gh-pages

